// Generated by jextract

package com.ustermetrics.ecos.stubs;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$0 {

    static final FunctionDescriptor ECOS_setup$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ECOS_setup$MH = RuntimeHelper.downcallHandle(
        "ECOS_setup",
        constants$0.ECOS_setup$FUNC, false
    );
    static final FunctionDescriptor ECOS_solve$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ECOS_solve$MH = RuntimeHelper.downcallHandle(
        "ECOS_solve",
        constants$0.ECOS_solve$FUNC, false
    );
    static final FunctionDescriptor ECOS_cleanup$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle ECOS_cleanup$MH = RuntimeHelper.downcallHandle(
        "ECOS_cleanup",
        constants$0.ECOS_cleanup$FUNC, false
    );
    static final FunctionDescriptor ECOS_ver$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle ECOS_ver$MH = RuntimeHelper.downcallHandle(
        "ECOS_ver",
        constants$0.ECOS_ver$FUNC, false
    );
}


